server:
  port: 0

spring:
  application:
    name: resource-server  # Eureka'ya kayıt olacak servis adı
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/templatesecurityapp
          jwk-set-uri: http://localhost:8080/realms/templatesecurityapp/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server'ın adresi
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Tüm endpoint'leri aç