server:
  port: 8081

spring:
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/templatesecurityapp
          jwk-set-uri: http://localhost:8080/realms/templatesecurityapp/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG